CREATE TABLE `ksei_ownership` (
	`id` text PRIMARY KEY NOT NULL,
	`code` text NOT NULL,
	`type` text NOT NULL,
	`report_date` integer NOT NULL,
	`total_shares` real NOT NULL,
	`price` real,
	`local_is` real,
	`local_cp` real,
	`local_pf` real,
	`local_ib` real,
	`local_id` real,
	`local_mf` real,
	`local_sc` real,
	`local_fd` real,
	`local_ot` real,
	`local_total` real,
	`foreign_is` real,
	`foreign_cp` real,
	`foreign_pf` real,
	`foreign_ib` real,
	`foreign_id` real,
	`foreign_mf` real,
	`foreign_sc` real,
	`foreign_fd` real,
	`foreign_ot` real,
	`foreign_total` real
);
